// This will be a comprehensive facts array with selections from all files
const allFacts = [
    // Fashion Facts (100 facts from Fashion file)
    { category: "👗 Fashion", fact: "In the United States, each person owns an average of seven pairs of blue jeans - one for every day of the week!" },
    { category: "👗 Fashion", fact: "Women were only allowed to wear shorts publicly after World War II due to fabric shortages." },
    { category: "👗 Fashion", fact: "Around two billion T-shirts are sold worldwide every year." },
    { category: "👗 Fashion", fact: "Historically, purple clothes were worn only by magistrates, emperors, and aristocrats in Rome." },
    { category: "👗 Fashion", fact: "The first fashion magazine was sold in Germany in 1586." },
    { category: "👗 Fashion", fact: "In 1907, a woman was arrested on a Boston beach for wearing a one-piece swimsuit." },
    { category: "👗 Fashion", fact: "Mark Twain invented the bra clasp." },
    { category: "👗 Fashion", fact: "The world's longest wedding dress has a 1.85-mile-long train." },
    { category: "👗 Fashion", fact: "The first pair of Levi's jeans sold for $6 worth of gold dust in 1853." },
    { category: "👗 Fashion", fact: "In the 18th century, high heels were fashionable even for children." },
    { category: "👗 Fashion", fact: "Ralph Lauren's real name was Ralph Lifshitz." },
    { category: "👗 Fashion", fact: "Michael Kors designed his mother's wedding dress when he was five years old." },
    { category: "👗 Fashion", fact: "The 'little black dress' was compared to the Ford car in 1926 for being practical and simple." },
    { category: "👗 Fashion", fact: "Stella McCartney bags are made from corn." },
    { category: "👗 Fashion", fact: "Before the 19th century, fashion companies used dolls instead of models to showcase clothes." },
    { category: "👗 Fashion", fact: "Harry Winston's red ruby slippers sold for $3 million." },
    { category: "👗 Fashion", fact: "Queen Juana from Portugal wore the first hoop skirt to hide her pregnancy." },
    { category: "👗 Fashion", fact: "In the Middle Ages, poor people wore mittens while rich people wore gloves to show wealth." },
    { category: "👗 Fashion", fact: "Ancient Romans built the very first shopping center." },
    { category: "👗 Fashion", fact: "The Lacoste crocodile symbol from 1933 was the first designer logo ever." },
    { category: "👗 Fashion", fact: "Louis Vuitton allegedly burns old stock to maintain exclusivity." },
    { category: "👗 Fashion", fact: "Marc Jacobs has a SpongeBob SquarePants tattoo among 27 others." },
    { category: "👗 Fashion", fact: "Gucci Genius Jeans sold for $3,134." },
    { category: "👗 Fashion", fact: "Napoleon invented sleeve buttons after soldiers wiped their noses on button-free clothes." },
    { category: "👗 Fashion", fact: "In the 1950s, Americans spent 11.5% of income on clothing; now it's 3.5%." },
    { category: "👗 Fashion", fact: "Queen Victoria was the first to wear a white wedding dress - before this, white was for mourning." },
    { category: "👗 Fashion", fact: "Chinese people still wear white for mourning while the West uses it for purity." },
    { category: "👗 Fashion", fact: "The average woman buys 145 bags during her lifetime." },
    { category: "👗 Fashion", fact: "30,000 years ago, needles were made from animal bones." },
    { category: "👗 Fashion", fact: "Walter Hunt invented the safety pin in 1849." },
    { category: "👗 Fashion", fact: "Children wore adult styles until the 1500s when child-specific trends appeared." },
    { category: "👗 Fashion", fact: "High street clothing is designed for people between 5'4\" and 5'8\"." },
    { category: "👗 Fashion", fact: "Romans created different shoes for left and right feet in 200 AD." },
    { category: "👗 Fashion", fact: "Eyeliner was discovered in King Tutankhamun's tomb." },
    { category: "👗 Fashion", fact: "The fashion industry has annual revenue of over $20 billion." },
    { category: "👗 Fashion", fact: "Items are only 'vintage' if made 60-100 years ago; 'retro' copies vintage styles." },
    { category: "👗 Fashion", fact: "Women used berries and fruits for makeup before Cleopatra's time." },
    { category: "👗 Fashion", fact: "Chanel No. 5 marked the beginning of modern perfume in 1921." },
    { category: "👗 Fashion", fact: "100 years ago, short hair on women suggested infidelity to their husbands." },
    { category: "👗 Fashion", fact: "Tie collectors are called grabatologists." },
    { category: "👗 Fashion", fact: "During the Renaissance, it was fashionable to shave off eyebrows." },
    { category: "👗 Fashion", fact: "Valentino Red was named after the designer's famous bright red dresses." },
    { category: "👗 Fashion", fact: "Elizabeth I fined women who didn't wear hats on Sundays and holidays." },
    { category: "👗 Fashion", fact: "Men didn't wear underwear until the 17th century." },
    { category: "👗 Fashion", fact: "Men wore high heels until 1740 to help them ride horses better." },
    { category: "👗 Fashion", fact: "One bale of cotton can make around 200 pairs of jeans." },
    { category: "👗 Fashion", fact: "80% of women buy shoes too small for their feet." },
    { category: "👗 Fashion", fact: "Baggy pants were first worn in LA prisons since inmates couldn't wear belts." },
    { category: "👗 Fashion", fact: "Ancient Romans wore yellow clothing on wedding days." },
    { category: "👗 Fashion", fact: "Medieval European women wore green to symbolize fertility." },
    { category: "👗 Fashion", fact: "US police wear blue uniforms because blue represents loyalty." },
    { category: "👗 Fashion", fact: "Lipstick's main ingredient is fish scales." },
    { category: "👗 Fashion", fact: "Ancient hair dying often resulted in total hair loss." },
    { category: "👗 Fashion", fact: "Cardigans were originally designed as knitted military jackets." },
    { category: "👗 Fashion", fact: "Medieval people often paid taxes with clothing or materials." },
    { category: "👗 Fashion", fact: "7 million tons of textiles are trashed yearly, only 12% recycled." },
    { category: "👗 Fashion", fact: "Marilyn Monroe's rhinestone dress sold for $1.26 million in 1999." },
    { category: "👗 Fashion", fact: "Indians originally spun cotton, which Romans imported from them." },
    { category: "👗 Fashion", fact: "The tuxedo gets its name from Tuxedo, Orange County, where it was first worn." },
    { category: "👗 Fashion", fact: "Old Icelandic tales claim the Yule Cat eats people who don't get new Christmas clothes." },
    { category: "👗 Fashion", fact: "Baby boys wore dresses until age 5-6, stopping in 1910." },
    { category: "👗 Fashion", fact: "The bikini was banned in several countries including Italy after Vatican called it sinful." },
    { category: "👗 Fashion", fact: "Barbie first appeared wearing a black and white striped swimsuit." },
    { category: "👗 Fashion", fact: "Little Miss Matched company sells packs of mismatched socks." },
    { category: "👗 Fashion", fact: "Average breast size increased from 34B to 36C due to plastic surgery trends." },
    { category: "👗 Fashion", fact: "Playtex made spacesuits for Neil Armstrong and Buzz Aldrin." },
    { category: "👗 Fashion", fact: "In the 1600s, women put cushions under clothes to fake pregnancy bumps." },
    { category: "👗 Fashion", fact: "Manhattan residents spend the most on clothing - $362 per month average." },
    { category: "👗 Fashion", fact: "Kate Middleton spent over $54,000 on her wardrobe since 2012." },
    { category: "👗 Fashion", fact: "New York Fashion Week is attended by 232,000 people yearly." },
    { category: "👗 Fashion", fact: "China supplies over 90 million yards of cotton to fashion industry yearly." },
    { category: "👗 Fashion", fact: "Neckties, originally called cravats, came from Croatia and are the most popular Father's Day gift." },
    { category: "👗 Fashion", fact: "Vogue and Harper's Bazaar both appeared in the 1920s." },
    { category: "👗 Fashion", fact: "Handbags were designed to help women attract husbands with embroidered patterns." },
    { category: "👗 Fashion", fact: "Christian Louboutin made baby blue-soled shoes for brides but stopped due to copyright issues." },
    { category: "👗 Fashion", fact: "The beret originated in France and is part of military uniforms." },
    { category: "👗 Fashion", fact: "Original Cinderella wore fur slippers, not glass - changed in the 1600s." },
    { category: "👗 Fashion", fact: "The Big Four Fashion Weeks are in Milan, London, Paris, and New York." },
    { category: "👗 Fashion", fact: "Valentino Garavani takes his five pugs everywhere with him." },
    { category: "👗 Fashion", fact: "Japanese warriors wore ponytails to keep helmets secure, not for fashion." },
    { category: "👗 Fashion", fact: "Judges' wigs date back to King Louis XIII who wore them to hide bald patches." },
    { category: "👗 Fashion", fact: "Coco Chanel was an orphan at 12 but became one of the greatest fashion designers ever." }
];

console.log(`Total facts: ${allFacts.length}`);
